UMDS .NET API: com.latencybusters.umds.UMDSServerThread Class Reference
com.latencybusters.umds.UMDSServerThread Class Reference
class UMDSServerThread is the internal class for managing the UMDS thread.
Public Member Functions
bool IsAlive ()
UMDSServerThread (UMDSServerConnection sc)
Constructor for the server thread object.
void start ()
void Run ()
Detailed Description
class UMDSServerThread is the internal class for managing the UMDS thread.
Constructor & Destructor Documentation
com.latencybusters.umds.UMDSServerThread.UMDSServerThread (UMDSServerConnection sc)
Constructor for the server thread object.
the UMDS exception
Exceptions
UMDSException
Parameters
sc The server connection this thread is to service.
References com.latencybusters.umds.UMDSMessage.appdata, com.latencybusters.umds.UMDSMessage.appmeta_data, com.latencybusters.umds.UMDSMessage.appmetadata_present, com.latencybusters.umds.UMDSServerConnection.Authenticated, com.latencybusters.umds.UMDSMessage.MSG_TYPE.CONFIGURATION_ERROR, com.latencybusters.umds.UMDSMessage.MSG_TYPE.CONNECT, com.latencybusters.umds.UMDS.LOG_LEVEL.CRITICAL, com.latencybusters.umds.UMDSMessage.MSG_TYPE.DATA, com.latencybusters.umds.UMDSMessage.MSG_TYPE.DISCONNECT, com.latencybusters.umds.UMDS.dlog(), com.latencybusters.umds.UMDS.LOG_LEVEL.INFO, com.latencybusters.umds.UMDSMessage.MSG_TYPE.LOGIN_COMPLETE, com.latencybusters.umds.UMDSMessage.MSG_TYPE.LOGIN_DENIED, com.latencybusters.umds.UMDSMessage.MSG_TYPE.LOGOUT_COMPLETE, com.latencybusters.umds.UMDSMessage.MSG_TYPE.LOSS, com.latencybusters.umds.UMDSMessage.low_seqnum, com.latencybusters.umds.UMDSServerConnection.onEvent(), com.latencybusters.umds.UMDSReceiverBase.onRequest(), com.latencybusters.umds.UMDSServerConnection.onRequest(), com.latencybusters.umds.UMDSSourceBase.onResponse(), com.latencybusters.umds.UMDSServerConnection.onResponse(), com.latencybusters.umds.UMDSMessageFormatter.parse(), com.latencybusters.umds.UMDSMessage.MSG_TYPE.RECEIVER_CREATE, com.latencybusters.umds.UMDSMessage.MSG_TYPE.RECEIVER_DELETE, com.latencybusters.umds.UMDSMessage.recovered, com.latencybusters.umds.UMDSMessage.MSG_TYPE.REQUEST, com.latencybusters.umds.UMDSMessage.MSG_TYPE.REQUEST_CANCELED, com.latencybusters.umds.UMDSMessage.requestID, com.latencybusters.umds.UMDSMessage.MSG_TYPE.RESPONSE, com.latencybusters.umds.UMDSMessage.response_data, com.latencybusters.umds.UMDSMessage.seqnum, com.latencybusters.umds.UMDSMessage.MSG_TYPE.SERVER_DENIED, com.latencybusters.umds.UMDSMessage.MSG_TYPE.SERVER_STOPPED, com.latencybusters.umds.UMDSServerConnection.setProperty(), com.latencybusters.umds.UMDSReceiverRecoveryInfoCallback.setReceiverRecoverySequenceNumber(), com.latencybusters.umds.UMDSMessage.MSG_TYPE.SOURCE_CREATE, com.latencybusters.umds.UMDSMessage.MSG_TYPE.SOURCE_DELETE, com.latencybusters.umds.UMDSMessage.srcidx, com.latencybusters.umds.UMDSMessage.topic, com.latencybusters.umds.UMDSMessage.type, com.latencybusters.umds.UMDSServerConnection.UMDS, and com.latencybusters.umds.UMDS.LOG_LEVEL.WARN.
The documentation for this class was generated from the following file:
UMDSServerThread.cs