UMDS .NET API: com.latencybusters.umds.UMDS Class Reference
com.latencybusters.umds.UMDS Class Reference
Base functionality for UMDS clients.
Inherited by com.latencybusters.umds.UMDSTestApp.xUMDS.
Classes
class DEBUG_FLAG
The DEBUG_FLAG interface is used to indicate the functionality a message is associated with for debug logs. Each value represents a bit in the debug mask. It is designed for internal usage only.
class ERRCODE
The ERRCODE class collects the standard error codes to be used with the UMDS client API. All client error codes shall be 32 bits (int). Errcodes generated from the server will have the SERVER_STATUS bit set to differentiate if the error is from the client or server side. Applications can simply cast to an int to get the real error and mask against SERVER_STATUS to determine of the error came from the server if they care.
class LOG_LEVEL
Collection of int values for the logging level.
class UMDSAuthenticationException
Exception used to indicate the connection is unauthorised.
class UMDSBadStateException
Exception used to indicate the connection is unauthorised.
class UMDSCapabilitiesException
Exception used to indicate a required capability is not allowed.
class UMDSDisconnectException
Exception used to indicate the connection ended.
class UMDSException
The base class for UMDS exception handling. It provides additional debugging capabilities in the form of storing exception stack traces for later dumping.
class UMDSNoDataException
Exception used to indicate there was no data when an operation expected some.
class UMDSPermissionsException
Exception used to indicate an operation is not permitted.
class UMDSReadTimeoutException
Exception used to indicate a read on the connect timed out - internal only.
class umdsTextNumberFormat
Public Member Functions
long TimeAsMillis ()
UMDS ()
Constructor for base UMDS class. Currently empty.
virtual void dlog (int level, System.String comment)
Log a message or a debug log. dlog() can be called even after close()
virtual void log (int level, System.String comment)
Log a message with a given log level. Applications can override this method if they need to add log level control. By default, all logs are output to System.err. log() can be called even after close()
void close ()
Terminate a UMDS global object and all references to it.
void RDDump (byte[] buf)
void WDDump (byte[] buf)
void SetDebugMask (long mask)
Set the debug level. This is used in cooperation with support.
Static Public Member Functions
static System.String version ()
Get the version string.
Properties
virtual System.String DebugLocation [set]
Set the location debug out put should sent.
Detailed Description
Base functionality for UMDS clients.
Member Function Documentation
void com.latencybusters.umds.UMDS.close ()
Terminate a UMDS global object and all references to it.
the UMDS exception
Exceptions
UMDSException
virtual void com.latencybusters.umds.UMDS.dlog (int level, System.String comment) virtual
Log a message or a debug log. dlog() can be called even after close()
See also
LOG_LEVEL
Parameters
level The level of the log comment (LOG_LEVEL)
comment The comment to be logged
Referenced by com.latencybusters.umds.UMDSServerConnection.getUMDS(), com.latencybusters.umds.UMDSMessageFormatter.parse(), com.latencybusters.umds.UMDS.UMDSException.UMDSException(), com.latencybusters.umds.UMDSMessageFormatter.UMDSMessageFormatter(), and com.latencybusters.umds.UMDSServerThread.UMDSServerThread().
virtual void com.latencybusters.umds.UMDS.log (int level, System.String comment) virtual
Log a message with a given log level. Applications can override this method if they need to add log level control. By default, all logs are output to System.err. log() can be called even after close()
See also
LOG_LEVEL
Parameters
level The level of the log comment (LOG_LEVEL)
comment The comment to be logged
Referenced by com.latencybusters.umds.UMDSServerConnection.getUMDS(), com.latencybusters.umds.UMDSReceiverBase.log(), and com.latencybusters.umds.UMDSSourceBase.log().
void com.latencybusters.umds.UMDS.SetDebugMask (long mask)
Set the debug level. This is used in cooperation with support.
the UMDS exception
Exceptions
UMDSException
Parameters
mask The debug mask.
Property Documentation
virtual System.String com.latencybusters.umds.UMDS.DebugLocation set
Set the location debug out put should sent.
the UMDS exception
Exceptions
UMDSException
The documentation for this class was generated from the following file:
UMDS.cs