UMDS .NET API: com.latencybusters.umds.UMDSMessageFormatter Class Reference
com.latencybusters.umds.UMDSMessageFormatter Class Reference
class UMDSMessageFormatter is the class which generates UMDSInternalMessages for UMDS clients.
Classes
class CtrlHdrFlags
class CtrlHdrID
class DataHdrFlags
class DataHdrID
class GenMsgHdrFormatter
class HdrSize
class MsgType
Public Member Functions
UMDSMessageFormatter (UMDSServerConnection sc)
Create a message formatter for a server connection.
virtual UMDSInternalMessage parse (System.IO.Stream instrm, long timeout)
Parse an input stream and create a message on the incoming stream.
Detailed Description
class UMDSMessageFormatter is the class which generates UMDSInternalMessages for UMDS clients.
Constructor & Destructor Documentation
com.latencybusters.umds.UMDSMessageFormatter.UMDSMessageFormatter (UMDSServerConnection sc)
Create a message formatter for a server connection.
Parameters
sc The server connection this message formatter is to be associated with.
References com.latencybusters.umds.UMDS.dlog(), and com.latencybusters.umds.UMDSServerConnection.UMDS.
Member Function Documentation
virtual UMDSInternalMessage com.latencybusters.umds.UMDSMessageFormatter.parse (System.IO.Stream instrm, long timeout) virtual
Parse an input stream and create a message on the incoming stream.
Parameters
instrm The input stream containing the message data
timeout The absolute time that the message should be parsed by (timeout).
References com.latencybusters.umds.UMDS.dlog().
Referenced by com.latencybusters.umds.UMDSServerThread.UMDSServerThread().
The documentation for this class was generated from the following file:
UMDSMessageFormatter.cs