UMDS Java API: com.latencybusters.umds.UMDSReceiver Class Reference
com.latencybusters.umds.UMDSReceiver Class Reference
Public Member Functions
UMDSReceiver (UMDSServerConnection sconn, String topic) throws UMDSException
UMDSReceiver (UMDSServerConnection sconn, String topic, boolean iswildcard) throws UMDSException
void onMessage (UMDSMessage msg)
void onEvent (UMDSMessage msg)
void onRequest (UMDSMessage msg)
final void close () throws UMDSException
void log (int level, String comment)
Object getReceiverRecoveryInfoCbArg ()
Protected Attributes
UMDSReceiverRecoveryInfoCallback receiverRecoveryInfoCb = null
Object receiverRecoveryInfoCbArg = null
UMDSServerConnection server
String topic
Detailed Description
class UMDSReceiver is the receiving class for UMDS receivers. Applications shall derive from it to implement their receiving object. Applications must override the onMessage() API to receive data.
Separate constructors are defined for regular and wildcard receivers. Applications have the choice of using the wildcard constructor or the UMDSWildcardReceiver class to implement wildcard receivers.
Constructor & Destructor Documentation
com.latencybusters.umds.UMDSReceiver.UMDSReceiver (UMDSServerConnection sconn, String topic) throws UMDSException
This constructor creates a regular receiver object on a UMDS connection.
Parameters
sconn The server connection object this receiver is tied to. This explicitly ties the receiver to a server.
topic The topic this receiver is receiving on
Exceptions
UMDSException the UMDS exception
com.latencybusters.umds.UMDSReceiver.UMDSReceiver (UMDSServerConnection sconn, String topic, boolean iswildcard) throws UMDSException
This constructor creates a wildcard receiver object on a UMDS connection when iswildcard is set to true. Applications may alternatively inherit UMDSWildcardReceiver which implicitly calls this constructor.
Parameters
sconn The server connection object this receiver is tied to. This explicitly ties the receiver to a server.
topic The topic this receiver is receiving on
iswildcard Indicates this receiver is a wildcard topic
Exceptions
UMDSException the UMDS exception
References com.latencybusters.umds.UMDSReceiver.onMessage().
Member Function Documentation
final void com.latencybusters.umds.UMDSReceiver.close () throws UMDSException
Close this receiver. The server will send an asynchronous ACK for this operation, queued messages will be received before the ACK is delivered.
Exceptions
UMDSException When the receiver could not be cleanly deleted
void com.latencybusters.umds.UMDSReceiverBase.log (int level, String comment) inherited
Log a receiver related message. This API currently does nothing unique, but is provided as an aid to users deriving from the class but may in the future be updated to identify the receiver automatically.
Exceptions
UMDSException the UMDS exception
void com.latencybusters.umds.UMDSReceiver.onEvent (UMDSMessage msg)
Event Notification function. This function is called when non-data events occur, E.G. Loss reported by the server.
This should be overridden by applications.
Expected message types: LOSS, DISCONNECT, SERVER_DENIED, RECEIVER_CREATE and RECEIVER_DELETE.
Parameters
msg The message containing the event
References com.latencybusters.umds.UMDSMessage.MSG_STATUS.CLOSE_PENDING, com.latencybusters.umds.UMDSMessage.MSG_TYPE.DISCONNECT, com.latencybusters.umds.UMDS.LOG_LEVEL.INFO, com.latencybusters.umds.UMDSMessage.MSG_TYPE.LOSS, com.latencybusters.umds.UMDSMessage.MSG_TYPE.RECEIVER_CREATE, com.latencybusters.umds.UMDSMessage.MSG_TYPE.RECEIVER_DELETE, com.latencybusters.umds.UMDSMessage.seqnum, com.latencybusters.umds.UMDSMessage.MSG_TYPE.SERVER_DENIED, com.latencybusters.umds.UMDSMessage.srcidx, com.latencybusters.umds.UMDSMessage.status, com.latencybusters.umds.UMDSMessage.status_str, and com.latencybusters.umds.UMDSMessage.type.
void com.latencybusters.umds.UMDSReceiver.onMessage (UMDSMessage msg)
Message Delivery function. This is called to deliver messages to the application.
This should be overridden by applications.
Only data messages will be given to onMessage()
See also
onEvent
Parameters
msg The message containing the received data
References com.latencybusters.umds.UMDSMessage.length(), and com.latencybusters.umds.UMDS.LOG_LEVEL.WARN.
Referenced by com.latencybusters.umds.UMDSReceiver.UMDSReceiver().
void com.latencybusters.umds.UMDSReceiver.onRequest (UMDSMessage msg)
Callback for request messages received. Implement this method to receive requests. Expected message types: REQUEST.
Parameters
msg The type for request messages is REQUEST. All UMDSMessage interfaces that are valid for DATA messages are also valid for request messages. The requestID is undefined for received requests, as it is a source-side-only correlation ID.
References com.latencybusters.umds.UMDS.LOG_LEVEL.WARN.
Member Data Documentation
UMDSServerConnection com.latencybusters.umds.UMDSReceiverBase.server protected inherited
The UMDS Server Connection associated with this receiver
String com.latencybusters.umds.UMDSReceiverBase.topic protected inherited
This receivers interested topic
The documentation for this class was generated from the following file:
UMDSReceiver.java